### PR TITLE
Fix crap login throttling

### LINKED ISSUE #1849: Improve throttling
`Illuminate\Routing\Middleware\ThrottleRequests` is a bit crap. I'm going to do a new major version of my throttling package that uses Laravel's native stuff though. We can switch back to that.

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Uses https://github.com/AltThree/Throttle, which still uses Laravel's rate limiter under the hood.

---

Closes #1849.

### CODE REVIEW

File: app/Foundation/Exceptions/Displayers/ThrottleDisplayer.php [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+ */
+
+namespace CachetHQ\Cachet\Foundation\Exceptions\Displayers;
+
+use Exception;
+use GrahamCampbell\Exceptions\Displayers\DisplayerInterface;
+use Illuminate\Http\Request;
+use Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException;
+
+class ThrottleDisplayer implements DisplayerInterface
```
Comment (GrahamCampbell) [inline app/Foundation/Exceptions/Displayers/ThrottleDisplayer.php]: This class basically says, if throttling occurred on an auth route, go back to the login page with a translated rate limit flash message.

File: resources/lang/en/forms.php [hunk 2]
```diff
@@ -34,6 +34,7 @@
         'invalid'       => 'Invalid username or password',
         'invalid-token' => 'Invalid token',
         'cookies'       => 'You must enable cookies to login.',
+        'rate-limit'    => 'Rate limit exceeded.',
```
Comment (GrahamCampbell) [inline resources/lang/en/forms.php]: @jbrooksuk Note the addition of this translation.
